# Generated by Django 5.2.17 on 2026-09-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gotra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
