# Generated by Django 5.2.17 on 2026-09-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_gotra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gotra',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
