# Generated by Django 5.2.17 on 2026-08-23 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('temples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringDonation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_id', models.CharField(max_length=100, unique=True)),
                ('category_name', models.CharField(default='Nitya Annadanam Seva', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interval', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20)),
                ('payment_method', models.CharField(default='UPI Autopay', max_length=50)),
                ('next_deduction_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('temple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_subscriptions', to='temples.temple')),
            ],
        ),
    ]
