# Generated by Django 5.2.17 on 2026-09-05 04:52

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('short_title', models.CharField(blank=True, max_length=100)),
                ('initiative_type', models.CharField(choices=[('TEMPLE_CONSTRUCTION', 'Temple Construction'), ('TEMPLE_RENOVATION', 'Temple Renovation'), ('TEMPLE_EXPANSION', 'Temple Expansion'), ('MATHA_DEVELOPMENT', 'Matha Development'), ('ANNADANAM', 'Annadanam'), ('EDUCATION', 'Education'), ('SCHOLARSHIPS', 'Scholarships'), ('MEDICAL_ASSISTANCE', 'Medical Assistance'), ('COMMUNITY_WELFARE', 'Community Welfare'), ('EMERGENCY_RELIEF', 'Emergency Relief'), ('INFRASTRUCTURE', 'Infrastructure'), ('RELIGIOUS_ACTIVITIES', 'Religious Activities'), ('CULTURAL_PROGRAMS', 'Cultural Programs'), ('DEVOTEE_SUPPORT', 'Devotee Support'), ('OTHER', 'Other')], default='TEMPLE_CONSTRUCTION', max_length=50)),
                ('custom_type', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField()),
                ('objective', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('is_urgent', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('has_physical_location', models.BooleanField(default=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('current_raised', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('donor_count', models.PositiveIntegerField(default=0)),
                ('min_donation', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('suggested_amounts', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True)),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('current_stage', models.CharField(choices=[('PROPOSED', 'Proposed & Planning'), ('FOUNDATION', 'Foundation & Bhoomi Pooja'), ('STRUCTURE', 'Structural Works'), ('FINISHING', 'Finishing & Sanctum'), ('COMPLETED', 'Completed & Consecrated')], default='PROPOSED', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('PUBLISHED', 'Published'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=30)),
                ('excess_funds_policy', models.TextField(blank=True, default='Excess funds collected will be utilized transparently for continuous Matha Annadanam, devotee welfare, and educational scholarships under the supervision of Sri Vasavi Matha Trust.')),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('final_report', models.TextField(blank=True, null=True)),
                ('completion_images', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_initiatives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InitiativeAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('previous_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='initiatives.initiative')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InitiativeBreakdownItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=150)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_items', to='initiatives.initiative')),
            ],
            options={
                'ordering': ['order', 'category'],
            },
        ),
        migrations.CreateModel(
            name='InitiativeExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField()),
                ('invoice_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_url', models.URLField(blank=True, max_length=500, null=True)),
                ('expense_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='initiatives.initiative')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InitiativeUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('images', models.JSONField(blank=True, default=list)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='initiatives.initiative')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
    ]
