# Generated by Django 5.2.17 on 2026-09-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='broadcast_on_publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='is_teaser_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='muhurtham_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('PUBLISHED', 'Published'), ('SCHEDULED', 'Scheduled Release'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=30),
        ),
    ]
