/**
 * Vedic Astrological & Devotional Constants
 */

export const VEDIC_NAKSHATRAS = [
  'Ashwini',
  'Bharani',
  'Krittika',
  'Rohini',
  'Mrigashira',
  'Ardra',
  'Punarvasu',
  'Pushya',
  'Ashlesha',
  'Magha',
  'Purva Phalguni',
  'Uttara Phalguni',
  'Hasta',
  'Chitra',
  'Swati',
  'Vishakha',
  'Anuradha',
  'Jyeshtha',
  'Mula',
  'Purva Ashadha',
  'Uttara Ashadha',
  'Shravana',
  'Dhanishta',
  'Shatabhisha',
  'Purva Bhadrapada',
  'Uttara Bhadrapada',
  'Revati',
] as const;

export const VEDIC_GOTRAS = [
  'Agastya',
  'Angirasa',
  'Atri',
  'Bharadwaja',
  'Bhrigu',
  'Gargi',
  'Gautama',
  'Harita',
  'Jamadagni',
  'Kashyapa',
  'Kaundinya',
  'Kaushika',
  'Maharshi',
  'Mudgala',
  'Parashara',
  'Sandilya',
  'Sankrithi',
  'Shaunaka',
  'Shrivatsa',
  'Upamanyu',
  'Vadhula',
  'Vasishta',
  'Vishwamitra',
] as const;

export const VEDIC_RASHIS = [
  { value: 'Mesha', label: 'Mesha (మేషం / Aries)' },
  { value: 'Vrishabha', label: 'Vrishabha (వృషభం / Taurus)' },
  { value: 'Mithuna', label: 'Mithuna (మిథునం / Gemini)' },
  { value: 'Karkataka', label: 'Karkataka (కర్కాటకం / Cancer)' },
  { value: 'Simha', label: 'Simha (సింహం / Leo)' },
  { value: 'Kanya', label: 'Kanya (కన్య / Virgo)' },
  { value: 'Tula', label: 'Tula (తుల / Libra)' },
  { value: 'Vrishchika', label: 'Vrishchika (వృశ్చికం / Scorpio)' },
  { value: 'Dhanu', label: 'Dhanu (ధనుస్సు / Sagittarius)' },
  { value: 'Makara', label: 'Makara (మకరం / Capricorn)' },
  { value: 'Kumbha', label: 'Kumbha (కుంభం / Aquarius)' },
  { value: 'Meena', label: 'Meena (మీనం / Pisces)' },
] as const;
